* NWS

** NWS is an online news reader

   NWS is a php CMS to manage various XML (RSS, aTom, etc) news feeds
   and present them in a nice fashion. I made it to replace the online
   news services that I've been using, as they became bloated and
   crippled with spyware. It's really a barebones system, but I've
   been using it for weeks now, and it basically does what I want.

*** Features
   - AJAX asynchronous loading of the feeds (ie reload one single feed w/o reloading the whole page)
   - Grabs the most out of the description centent and displays it as standard tooltip on mouse hover
   - Does its best to parse any given feed and identify it w/o questions.
   - Plays nice with different resolutions & ergonomics, ie phones, tablets, etc
   - Links directly on any included image
   - If any, displays item image, wrapped around text (displays it full width if it's the only item's element)
   - Lightweight and standard (valid HTML5 code)

*** Installation
   - Copy the files in a directory within a webserver root. Point your browser to that directory
   - Recommended : Edit the .htaccess to protect (restrict access to) the back-office
     - Go to http://aspirine.org/htpasswd_en.html
     - Paste this user/password pair in a file, and upload it as nws/.access (or another location, see below)
     - You can also create user/password pair(s) directly on the server with the command "htpasswd -b .access username password"
     - Optional : Move the .access out of the http server root, and edit .htaccess to reflect this change.

*** Usage
   - Use "Pin as app tab" in Firefox to prevent tab clutter
   - Use the "mgmt" link to access the "back office"
     - Use the "add a new feed" text entry field at the bottom to enter a new feed
     - Use the "new tab" text entry field to create a new category
     - Use the "change this feed's tab" menu to re-categorize the feed
     - Use the "promote this feed" (^) link to bump up a feed as 1st of its tab
     - Use the "delete this feed" (x) link to delete a feed

*** +TODO
  - A better sorting system. Right now it's quite a PITA when you add a new feed and assign it to a category/tab, to promote (^) the feeds and tabs to their previous locations
  - A sqlite DB (in a ramdisk where applicable). This plain text file is nice and portable and all, but it's damn slow
  - Some way of listening linked audio files & feeds

*** LICENSE
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
